serial:
  port: /dev/ttyUSB0
  baudrate: 115200
# 以下为热加载
camera:
  id: 0
  width: 1280
  height: 720
  fps: 30
  exposure: 10.
  gain: 1.0
  wb_temprature: 4500
img:
  area:
    min: 15
    max: 170
  threshold: 245
  roi:
   ratio: 2.0
  other:
   led_offset: 11.14
   slope_duration_time: 5. # seconds